language: go

dist: xenial
sudo: required

go:
  - 1.13.x
  - 1.14.x
env:
  - GO111MODULE=on && TRAVIS_NODE_VERSION="14.15.3"

before_install:
  - go get golang.org/x/tools/cmd/goimports
  - nvm install TRAVIS_NODE_VERSION
  - nvm alias default TRAVIS_NODE_VERSION

script:
  - diff -u <(echo -n) <(gofmt -d -s .)
  - diff -u <(echo -n) <(goimports -d .)
  - go test -v -race ./... -coverprofile=coverage.txt -covermode=atomic
  - cd assets
  - npm install
  - npm run start

after_success:
  - bash <(curl -s https://codecov.io/bash)
