name: front

on:
  push:
    paths:
      - "assets/**"
      - ".github/**"
    branches:
      - master
  pull_request:
    paths:
      - "assets/**"
      - ".github/**"
    branches:
      - master

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
          cache-dependency-path: assets/package-lock.json
      - name: yarn build dist
        run: |
          cd assets
          yarn install
          yarn build
